### ISSUE TITLE
Transform function for INDIMCAR models

### ISSUE THREAD

**Issue by agila5** [becarioprecario/INLAMSM#2]
Dear Prof. Gómez-Rubio, this is again a minor issue but I was thinking that maybe it would be useful implementing a new function for transforming the hyperparameters of an INDIMCAR model into the original scale (i.e. the log precisions into variances). 

I know that the transformations are really easy (just function(x) exp(-x)) but I think that the function could still be useful for an easy comparison of the variances of the four types of model (INDIMCAR, IMCAR, PCAR and MMODEL).

**Comment by becarioprecario** [comment]
Hi,

Thanks. We could modify INLAMSM::inla.MCAR.transform to do that in the future.

Best,

Virgilio
