### ISSUE TITLE
Question on log.prior and a small typo (maybe)

### ISSUE THREAD

**Issue by agila5** [becarioprecario/INLAMSM#4]
Dear all, thank you very much for working on this R package. It helped me a lot. 

I created this github issue since I want to implement a (slightly different) multivariate CAR effect than what you defined in the package and, while I was studying your code, I faced some doubts/issues so I hope you can help me. I created a github issue instead of an email since here it's easier to show my doubts with the code, sorry if that's a problem. 

More precisely I don't understand the definition of the log.prior function in the MCAR and IMCAR generic cases: 

https://github.com/becarioprecario/INLAMSM/blob/706d8340e973407b7e0eb18d582f59ef9b7b0a65/R/MCAR_rgeneric.R#L298-L316

I read from [here](https://becarioprecario.bitbucket.io/inla-gitbook/ch-priors.html#sec:newpriors) and [here](https://becarioprecario.bitbucket.io/inla-gitbook/ch-newmodels.html) that the priors should be specified on theta (the internal representation of the parameters) and, if I define a prior using the natural scale of the parameters, then the internal prior on theta is obtained using the [transfomation of r.v. theorem](https://en.wikipedia.org/wiki/Random_variable#Functions_of_random_variables). For example, when you defined a uniform prior on the autocorrelation parameter, you defined that the prior on theta[1] (the internal representation of the autocorrelation parameter) is given by the derivative of the inverse of the transformation (i.e. `-theta[1] - 2 * log(1 + exp(-theta[1]))`) times a constant (i.e. the pdf of the uniform r.v.). I don't understand how to generalize and apply these ideas to the multivariate content (i.e. the Wishart distribution). Could you please explain the code from lines 307 to 313? 

Moreover, I think I found a small typo here: 

https://github.com/becarioprecario/INLAMSM/blob/706d8340e973407b7e0eb18d582f59ef9b7b0a65/R/indep_MCAR_rgeneric.R#L272-L273

since when you define the internal prior on the log-precisions I think you should consider `theta[-1]` or `theta[2:(k + 1)]`, i.e. exclude `theta[1]`, which is the autocorrelation parameter, from `theta`.

**Comment by becarioprecario** [comment]
Hi,

Many thanks for this and sorry for not going back to you sooner. This has been a bad year for many of us. You are right and this has now been fixed. Many thanks again and sorry for my late reply.
